# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Peggle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Peggle

  target 'PeggleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PeggleUITests' do
    # Pods for testing
  end

end
